import { Category } from "../types/Category";

export const CATEGORY_SLUGS: { [key: string]: Category } = {
  news: {
    apiEndpoint: "news/news",
    translation: "MedicineAndScienceNews",
    urlSlug: "news",
    translationDescr: "MedicineAndScienceNewsDescr",
  },
  reviews: {
    apiEndpoint: "news/reviews",
    translation: "ScientificArticlesReviews",
    urlSlug: "reviews",
    translationDescr: "ScientificArticlesReviewsDescr",
  },
  articles: {
    apiEndpoint: "news/articles",
    translation: "PopularScienceArticles",
    urlSlug: "articles",
    translationDescr: "PopularScienceArticlesDescr",
  },
  foodScience: {
    apiEndpoint: "news/food-science",
    translation: "FoodScience",
    urlSlug: "food-science",
    translationDescr: "",
  },
  clinicalCases: {
    apiEndpoint: "clinicalCases",
    translation: "ClinicalCases",
    urlSlug: "clinical-cases",
    translationDescr: "",
  },
  guidelines: {
    apiEndpoint: "guidelines",
    translation: "ClinicalGuidelines",
    urlSlug: "guidelines",
    translationDescr: "ClinicalGuidelinesPageDescr",
  },
  patientPhysicalExamination: {
    apiEndpoint: "physicalExamination",
    translation: "PatientPhysicalExamination",
    urlSlug: "patient-physical-examination",
    translationDescr: "PatientPhysicalExaminationDescr",
  },
  platformNews: {
    apiEndpoint: "news/platform-news",
    translation: "PlatformNews",
    urlSlug: "platform-news",
    translationDescr: "PlatformNewsDesc",
  },
  vacancies: {
    apiEndpoint: "vacancies",
    translation: "Vacancies",
    urlSlug: "vacancies",
    translationDescr: "",
  },
  modules: {
    apiEndpoint: "modules",
    translation: "Modules",
    translationForItem: "Module",
    urlSlug: "modules",
    translationDescr: "ModulesDescription",
  },
  moduleStages: {
    apiEndpoint: "moduleStages",
    translation: "",
    translationForItem: "",
    urlSlug: "stages",
    translationDescr: "",
  },
  moduleTestStageScore: {
    apiEndpoint: "",
    translation: "",
    translationForItem: "",
    urlSlug: "score",
    translationDescr: "",
  },
  getCertificate: {
    apiEndpoint: "api/v1/user/certification/get",
    translation: "",
    translationForItem: "",
    urlSlug: "",
    translationDescr: "",
  },
  videoLectures: {
    apiEndpoint: "lectures",
    translation: "VideoLectures",
    translationForItem: "VideoLecture",
    urlSlug: "lectures",
    translationDescr: "VideoLecturesDescription",
  },
  videoLectureStages: {
    apiEndpoint: "lectureStages",
    translation: "",
    translationForItem: "",
    urlSlug: "stages",
    translationDescr: "",
  },
  podcasts: {
    apiEndpoint: "podcasts",
    translation: "Podcasts",
    urlSlug: "podcasts",
    translationDescr: "PodcastsDescr",
  },
  webinars: {
    apiEndpoint: "webinars",
    translation: "Webinars",
    urlSlug: "webinars",
    translationDescr: "WebinarsPageDescr",
  },
  events: {
    apiEndpoint: "events",
    translation: "Calendar",
    urlSlug: "events",
    translationDescr: "CalendarDescr",
  },
  aboutThePlatform: {
    apiEndpoint: "",
    translation: "AboutThePlatform",
    urlSlug: "about-the-platform",
    translationDescr: "",
  },
  eventLandingpage: {
    apiEndpoint: "eventLandings",
    translation: "",
    urlSlug: "event-landingpage",
    translationDescr: "",
  },
  faq: {
    apiEndpoint: "",
    translation: "FAQ",
    urlSlug: "faq",
    translationDescr: "",
  },
  advertising: {
    apiEndpoint: "",
    translation: "Advertising",
    urlSlug: "advertising-on-the-website",
    translationDescr: "",
  },
  subscribe: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "subscribe",
    translationDescr: "",
  },
  login: {
    apiEndpoint: "login",
    translation: "",
    urlSlug: "login",
    translationDescr: "",
  },
  requestPasswordReset: {
    apiEndpoint: "forgotPassword",
    translation: "",
    urlSlug: "request-password-reset",
    translationDescr: "",
  },
  requestPasswordConfirmation: {
    apiEndpoint: "resetPassword",
    translation: "",
    urlSlug: "reset",
    translationDescr: "",
  },
  registration: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "register",
    translationDescr: "",
  },
  accountSettings: {
    apiEndpoint: "",
    translation: "Settings",
    urlSlug: "account/settings",
    translationDescr: "",
  },
  accountEducation: {
    apiEndpoint: "",
    translation: "Education",
    urlSlug: "account/education",
    translationDescr: "",
  },
  accountCertificates: {
    apiEndpoint: "",
    translation: "MyCertificates",
    urlSlug: "account/certificates",
    translationDescr: "",
  },
  accountMain: {
    apiEndpoint: "",
    translation: "MainPage",
    urlSlug: "account/main",
    translationDescr: "",
  },
  accountLogOut: {
    apiEndpoint: "",
    translation: "LogOut",
    urlSlug: "account/logout",
    translationDescr: "",
  },
  accountFaq: {
    apiEndpoint: "",
    translation: "FAQ",
    urlSlug: "account/faq",
    translationDescr: "",
  },
  accountCommunityProfile: {
    apiEndpoint: "",
    translation: "CommunityProfile",
    urlSlug: "account/community-profile",
    translationDescr: "",
  },
  accountUserProfile: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "account/user",
    translationDescr: "",
  },
  accountPurchases: {
    apiEndpoint: "",
    translation: "MyPurchases",
    urlSlug: "account/purchases",
    translationDescr: "",
  },
  accountNotifications: {
    apiEndpoint: "notifications",
    translation: "Notifications",
    urlSlug: "account/notifications",
    translationDescr: "",
  },
  checkout: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "checkout",
    translationDescr: "",
  },
  infoPages: {
    apiEndpoint: "information",
    translation: "",
    urlSlug: "",
    translationDescr: "",
  },
  cookies: {
    apiEndpoint: "",
    translation: "Cookies",
    urlSlug: "cookies",
    translationDescr: "",
  },
  privacyPolicy: {
    apiEndpoint: "",
    translation: "PrivacyPolicy",
    urlSlug: "privacy-policy",
    translationDescr: "",
  },
  termsAndConditions: {
    apiEndpoint: "",
    translation: "TermsAndConditions",
    urlSlug: "terms-and-conditions",
    translationDescr: "",
  },
  communityRules: {
    apiEndpoint: "",
    translation: "CommunityRules",
    urlSlug: "community-rules",
    translationDescr: "",
  },
  search: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "search",
    translationDescr: "",
  },
  partners: {
    apiEndpoint: "partners",
    translation: "Partners",
    urlSlug: "partners",
    translationDescr: "",
  },
  community: {
    apiEndpoint: "community",
    translation: "Community",
    urlSlug: "community",
    translationDescr: "",
  },
  communityCreateTopic: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "community/create-topic",
    translationDescr: "",
  },
  communityTagTopics: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "community/tag-topics",
    translationDescr: "",
  },
  communityTopic: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "community/topic",
    translationDescr: "",
  },
  thankYouRegistration: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "success-create",
    translationDescr: "",
  },
  thankYouAccountActivation: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "activation",
    translationDescr: "",
  },
  thankYouEmailChange: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "success-update-email",
    translationDescr: "",
  },
  thankYouEmailUpdate: {
    apiEndpoint: "user/updateEmail",
    translation: "",
    urlSlug: "account/emailUpdate",
    translationDescr: "",
  },
  thankYouRequestPasswordReset: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "success-request-password-reset",
    translationDescr: "",
  },
  thankYouPasswordResetConfirmation: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "success-password-reset",
    translationDescr: "",
  },
  thankYouSubscribe: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "thanks/Subscribe",
    translationDescr: "",
  },
  thankYouPayment: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "success-payment",
    translationDescr: "",
  },
  page404: {
    apiEndpoint: "",
    translation: "",
    urlSlug: "404",
    translationDescr: "",
  },
};
